### ISSUE TITLE
Error in "show me some restaurants"

### ISSUE THREAD

**Issue by DevHerles** [RasaHQ/kb-demo-chatgpt#1]
Why occurs this error?

```shell
Your input ->  show me some restaurants
2023-04-03 15:06:21 WARNING  rasa.core.actions.action  - Failed to execute custom action 'action_show_restaurants' as a result of error 'Failed to execute custom action 'action_show_restaurants''. The default action 'action_extract_slots' failed to fill slots with custom mappings.
2023-04-03 15:06:21 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_show_restaurants'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/home/herles/.venv/rasa/lib/python3.8/site-packages/rasa/core/actions/action.py", line 770, in run
    response: Any = await self.action_endpoint.request(
  File "/home/herles/.venv/rasa/lib/python3.8/site-packages/rasa/utils/endpoints.py", line 175, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 404, Not Found, body='b'{"error":"No registered action found for name \'action_show_restaurants\'.","action_name":"action_show_restaurants"}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/herles/.venv/rasa/lib/python3.8/site-packages/rasa/core/processor.py", line 917, in _run_action
    events = await action.run(
  File "/home/herles/.venv/rasa/lib/python3.8/site-packages/rasa/core/actions/action.py", line 797, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_show_restaurants'
Your input ->
```
Previously I started:

```shell
devherles/rasa-chatgpt on  master [?] via 🐍 v3.8.10 (rasa)
❯ rasa run actions
2023-04-03 14:59:02 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2023-04-03 14:59:02 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055
2023-04-03 14:59:14 ERROR    rasa_sdk.endpoint  - No registered action found for name 'action_show_restaurants'.
2023-04-03 14:59:23 ERROR    rasa_sdk.endpoint  - No registered action found for name 'action_show_restaurants'.
2023-04-03 14:59:25 ERROR    rasa_sdk.endpoint  - No registered action found for name 'action_show_restaurants'.
```

Regards!

**Comment by DevHerles** [comment]
I restarted, and now it works like a charm!
